### ISSUE TITLE
Project building is broken: npm run dist

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/WebClients#130]
**Describe the bug**
Error during running `npm run dist` command.

**To Reproduce**
1. run `npm run config`
2. run `npm run dist`
3. See the following error in console:
```
ERROR in ./src/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './pages/' in '/dev/protonmail/WebClient/src/sass'
    at factory.create (/dev/protonmail/WebClient/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /dev/protonmail/WebClient/node_modules/neo-async/async.js:2825:7
    at /dev/protonmail/WebClient/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn43 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn3 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:42:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn4 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:51:1)
    at hook.callAsync (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn2 (eval at create (/dev/protonmail/WebClient/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at fs.stat (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:22:13)
    at process.nextTick (/dev/protonmail/WebClient/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)

```

**Expected behavior**
Project is buildable at any time.

**Additional context**
Building the project from sources.

**Analysis**
The project was buildable a few days ago, but right now build is broken even though there was no code changes. It's because the project doesn't have a lock file comitted. Some dependencies got updated which made build broken without actual code changes. See relative issue https://github.com/ProtonMail/WebClient/issues/116.

**Comment by vladimiry** [comment]
Btw the cause of the error is in loader-utils 1.1.0=>1.2.0 update happened 7 hours ago. The simplest workaround seems to be in adding loader-utils@1.1.0 to the dev dependencies section of the project, so it will have a priority for webpack stack. A lot of webpack related modules depend on loader-utils in general, hope only mini-css-extract-plugin got affected.

**Comment by vladimiry** [comment]
Also see this workaround https://github.com/cnpm/bug-versions/pull/30/files.

**Comment by vladimiry** [comment]
The project is buildable again with this issue resolved https://github.com/webpack/loader-utils/issues/133 and respective loader-utils@1.2.1 release.

But fulfilling the following expected behaviour would require enabling the dependencies locking:

> Expected behavior
Project is buildable at any time.

**Comment by ArcanisCz** [comment]
Imho, its caused by #116

**Comment by vladimiry** [comment]
Closing as duplicate of https://github.com/ProtonMail/WebClient/issues/116.
