### ISSUE TITLE
docker fails at the npm install step

### ISSUE THREAD

**Issue by pierreozoux** [ProtonMail/WebClients#17]
### Description or steps to reproduce the problem

`make start`

### Expected Behavior
Get access to the web app.

### Actual Behavior
I get a node error:

```
 ~/f/WebClient   public  make start
./bin/crun-node npm install --unsafe-perm --loglevel warn --no-bin-links
Resolving node version...
Error: No such image or container: node:5.11.1
Pulling node:5.11.1 image...
5.11.1: Pulling from library/node

5c90d4a2d1a8: Pull complete 
ab30c63719b1: Pull complete 
c6072700a242: Pull complete 
abb742d515b4: Pull complete 
22efa86cdb65: Pull complete 
6950894a9fa1: Pull complete 
Digest: sha256:d297df3a72889ca35fbf6f237a2c25dfa1c874cdcea332adc7a7a7fa8a955da6
Status: Downloaded newer image for node:5.11.1
+ docker run -v /home/pierre/f/WebClient:/home/pierre/f/WebClient -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e HOME=/home/pierre/f/WebClient -w /home/pierre/f/WebClient -e PATH=./node_modules/.bin/:./node_modules/grunt-cli/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --rm -ti --sig-proxy=true node:5.11.1 npm install --unsafe-perm --loglevel warn --no-bin-links
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--loglevel" "warn" "--no-bin-links"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pierre/f/WebClient/npm-debug.log
Makefile:8: recipe for target 'npm-install' failed
make: *** [npm-install] Error 1
```

Here are more details from the npm-debug.log:
```
70003 silly build setprototypeof@1.0.1
70004 verbose stack RangeError: Maximum call stack size exceeded
70004 verbose stack     at emitThree (events.js:110:13)
70004 verbose stack     at emit (events.js:188:7)
70004 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
70004 verbose stack     at emitThree (events.js:110:13)
70004 verbose stack     at emit (events.js:188:7)
70004 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
70004 verbose stack     at emitThree (events.js:110:13)
70004 verbose stack     at emit (events.js:188:7)
70004 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-group.js:23:18)
70004 verbose stack     at emitThree (events.js:110:13)
70004 verbose stack     at emit (events.js:188:7)
70005 verbose cwd /home/pierre/f/WebClient
70006 error Linux 4.4.0-45-generic
70007 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--loglevel" "warn" "--no-bin-links"
70008 error node v5.11.1
70009 error npm  v3.8.6
70010 error Maximum call stack size exceeded
70011 error If you need help, you may report this error at:
70011 error     <https://github.com/npm/npm/issues>
70012 verbose exit [ 1, true ]
```

**Comment by jpbochi** [comment]
should this be closed? There's no `Makefile` anymore and the code requires node `>=6` now.
