### ISSUE TITLE
unable to read node_modules/pt.blobjs 

### ISSUE THREAD

**Issue by lacivert** [ProtonMail/WebClients#55]
* Which browser (+ version) ? Chrome / Firefox / Safari / Opera
* Which OS (+ version)? Mac OS
* Which layout mode? Column mode / Row mode
* Which threading mode? Conversation mode / Message mode
* Can you reproduce the problem each time? Yes 
* Which url?

### What steps will reproduce the problem?

* 1) git pull
* 2) npm install
* 3) npm start

### What is the expected result?
it should be working?

### What happens instead?
does not work;

```
> protonmail-web@3.11.5 start /path/to/WebClient
> grunt watch --api=dev

Running "notify_hooks" task

Running "ngconstant:dev" (ngconstant) task
Creating module proton.config at src/app/config.js...OK

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "html2js:app" (html2js) task
Successfully converted 231 html templates to js.

Running "sass:build" (sass) task

Running "concat:build_css" (concat) task

Running "postcss:dist" (postcss) task
>> 2 processed stylesheets created.

Running "copy:build_app_assets" (copy) task
Created 16 directories, copied 142 files

Running "copy:build_appjs" (copy) task
Copied 545 files

Running "concat:build_js" (concat) task

Running "copy:build_vendorjs" (copy) task
Warning: Unable to read "node_modules/pt.blobjs/Blob.js" file (Error code: ENOENT). Use --force to continue.
```

### Please provide any additional information below. Attach a screenshot if possible.
I check the pt.blobjs in node_modules, there is no module directory there. There is nothing on package.json about it either. So it is missing somewhere somehow. Maybe we don't even need it but what should I do?

**Comment by dhoko** [comment]
Hey,

we install this dep via the script 'tasks/privateDependencies.sh'.  I had the same issue this afternoon, after another `$ npm i` it worked.

> We run the shell script via postinstall.

Can you try to re-run `$ npm i` ?

**Comment by lacivert** [comment]
I have just tried both npm i and sudo npm i, still same.

**Comment by dhoko** [comment]
Can you give me your npm.log ? You should see something inside the output from `$ npm i`.

**Comment by lacivert** [comment]
do you mean debug log?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.4.1
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle protonmail-web@3.11.5~prestart: protonmail-web@3.11.5
6 info lifecycle protonmail-web@3.11.5~start: protonmail-web@3.11.5
7 verbose lifecycle protonmail-web@3.11.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle protonmail-web@3.11.5~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/path/to/WebClient/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/Cellar/maven/3.5.0/libexec/bin
9 verbose lifecycle protonmail-web@3.11.5~start: CWD: /path/to/WebClient
10 silly lifecycle protonmail-web@3.11.5~start: Args: [ '-c', 'grunt watch --api=dev' ]
11 silly lifecycle protonmail-web@3.11.5~start: Returned: code: 3  signal: null
12 info lifecycle protonmail-web@3.11.5~start: Failed to exec start script
13 verbose stack Error: protonmail-web@3.11.5 start: `grunt watch --api=dev`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid protonmail-web@3.11.5
15 verbose cwd /Users/yasin/dev/WebClient
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.1.3
19 verbose npm  v5.4.1
20 error code ELIFECYCLE
21 error errno 3
22 error protonmail-web@3.11.5 start: `grunt watch --api=dev`
22 error Exit status 3
23 error Failed at the protonmail-web@3.11.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
```

**Comment by dhoko** [comment]
Nope what's inside the `$ npm i`.

Cf the output from `$ npm i`.
```
$ npm i                                                                                                   
                                                                                                          
> node-sass@4.5.3 install /home/dhoko/dev/taf/Angular/node_modules/node-sass                              
> node scripts/install.js                                                                                 
                                                                                                          
Cached binary found at /home/dhoko/.npm/node-sass/4.5.3/linux-x64-57_binding.node                         
                                                                                                          
> phantomjs-prebuilt@2.1.14 install /home/dhoko/dev/taf/Angular/node_modules/phantomjs-prebuilt           
> node install.js                                                                                         
                                                                                                          
PhantomJS not found on PATH                                                                               
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.
bz2                                                                                                       
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2                                             
Receiving...                                                                                              
  [======----------------------------------] 16%                                                          
Received 22866K total.                                                                                    
Extracting tar contents (via spawned process)                                                             
Removing /home/dhoko/dev/taf/Angular/node_modules/phantomjs-prebuilt/lib/phantom                          
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1509696813926/phantom
js-2.1.1-linux-x86_64 -> /home/dhoko/dev/taf/Angular/node_modules/phantomjs-prebuilt/lib/phantom          
Writing location.js file                                                                                  
Done. Phantomjs binary available at /home/dhoko/dev/taf/Angular/node_modules/phantomjs-prebuilt/lib/phanto
m/bin/phantomjs                                                                                           
                                                                                                            
> node-sass@4.5.3 postinstall /home/dhoko/dev/taf/Angular/node_modules/node-sass                            
> node scripts/build.js                                                                                     
                                                                                                            
Binary found at /home/dhoko/dev/taf/Angular/node_modules/node-sass/vendor/linux-x64-57/binding.node         
Testing binary                                                                                              
Binary is fine                                                                                              
                                                                                                            
> protonmail-web@3.11.7 postinstall /home/dhoko/dev/taf/Angular                                             
> ./tasks/privateDependencies.sh                                                                            
                                                                                                            
Cloning into 'node_modules/pt.blobjs'...                                                                    
remote: Counting objects: 5, done.                                                                          
remote: Compressing objects: 100% (5/5), done.                                                              
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0                                                
Receiving objects: 100% (5/5), done.                                                                        
Note: checking out '079824b6c118fbcd0b99c561d57ad192d2c6619b'.                                              
                                                                                                            
You are in 'detached HEAD' state. You can look around, make experimental                                    
changes and commit them, and you can discard any commits you make in this                                   
state without impacting any branches by performing another checkout.                                        
                                                                                                            
If you want to create a new branch to retain commits you create, you may                                    
do so (now or later) by using -b with the checkout command again. Example:                                  
                                                                                                           
  git checkout -b <new-branch-name>                                                                        
                                                                                                           
HEAD is now at bfb14fd... Bump v0.0.11                                                                     
/home/dhoko/dev/taf/Angular                                                                                
Cloning into 'node_modules/pt.qrcodejs'...                                                                 
remote: Counting objects: 12, done.                                                                        
remote: Compressing objects: 100% (10/10), done.                                                           
remote: Total 12 (delta 1), reused 7 (delta 1), pack-reused 0                                              
Receiving objects: 100% (12/12), 52.67 KiB | 0 bytes/s, done.                                              
Resolving deltas: 100% (1/1), done.                                                                        
Note: checking out '04f46c6a0708418cb7b96fc563eacae0fbf77674'.                                             
                                                                                                           
You are in 'detached HEAD' state. You can look around, make experimental                                   
changes and commit them, and you can discard any commits you make in this                                  
state without impacting any branches by performing another checkout.                                       
                                                                                                           
If you want to create a new branch to retain commits you create, you may                                   
do so (now or later) by using -b with the checkout command again. Example:                                 
                                                                                                           
  git checkout -b <new-branch-name>                                                                        
                                                                                                           
HEAD is now at 04f46c6... Merge pull request #63 from markvantilburg/patch-1                               
/home/dhoko/dev/taf/Angular                                                                                
                                                                                                           
--- custom dependencies installed ---                                                                      
                                                                                                           
added 1100 packages in 38.071s                                                                                                            

```

What's inside your output after `> ./tasks/privateDependencies.sh` ?

**Comment by TangKunjun** [comment]
I also encountered this problem, how to solve?

**Comment by dhoko** [comment]
You can comment the git clone inside `./tasks/privateDependencies.sh` and install the lib via `npm install blobjs`.

Then inside the file `env/conf.build.js`

```diff
- 'node_modules/pt.blobjs/Blob.js',
+ 'node_modules/blobjs/Blob.min.js',
```

It should work. The new version will be without a git clone, everything will come via npm.

**Comment by ghost** [comment]
@dhoko Yes, it work, we only need add small adjustments:

env/conf.build.js :

      /* 'node_modules/pt.qrcodejs/qrcode.js', */
      'node_modules/qrcode/build/qrcode.min.js',

      (...)

      /* 'node_modules/pt.asmcrypto.js/asmcrypto.js', */
      'node_modules/asmcrypto.js/asmcrypto.js',

$ npm install qrcode
$ npm install asmcrypto.js

Thank you.

**Comment by dhoko** [comment]
All changes to perform before the new release.

package.json

```diff
+    "asmcrypto.js": "https://github.com:vibornoff/asmcrypto.js.git#bfb14fdb4cecebd1ae260ae78e3663b8273120e1",
+    "blob.js": "^1.0.1",
+    "qrcodejs2": "0.0.2",
```

privateDependencies.sh
```sh
DEST_MAILPARSER='node_modules/pt.mailparser'

# Remove previous version
rm -rf $DEST_MAILPARSER

mkdir $DEST_MAILPARSER
cp src/libraries/mailparser.js $DEST_MAILPARSER/mailparser.js

echo
echo "--- custom dependencies installed ---"
echo
```

env/conf.build.js :
```diff
-      'node_modules/pt.blobjs/Blob.js',
+      'node_modules/blob.js/Blob.js',
-      'node_modules/pt.qrcodejs/qrcode.js',
+      'node_modules/qrcodejs2/qrcode.min.js',
-      'node_modules/pt.asmcrypto.js/asmcrypto.js',
+      'node_modules/asmcrypto.js/asmcrypto.js',
```

Voilà

**Comment by dhoko** [comment]
cf https://github.com/ProtonMail/WebClient/blob/public/tasks/privateDependencies.sh

Voilà, everything is coming from npm and the package.json :)
